<section>
    <div class="header-img"></div>
    <h1 class="title"><?php print $data['title'] ?></h1>
    <div class="content-container">
        <div class="flex-box">
            <div class="content-list">
                <img src="/media/images/gym.jpg" alt="image about gym">
                <h3>Best Gym</h3>
                <p>
                    A gymnasium, also known as a gym, is a covered location for athletics.
                    A gym is a place with a number of equipments and machines
                    used by the people to do exercises.
                </p>
            </div>
            <div class="content-list">
                <img src="/media/images/spa.jpg" alt="image about spa">
                <h3>Sauna after training</h3>
                <p>
                    A sauna is a small room or building designed as a place to experience dry or wet heat
                    sessions, or an establishment with one or more of these facilities.
                    The steam and high heat make the bathers perspire.
                </p>
            </div>
            <div class="content-list">
                <img src="/media/images/bar.jpg" alt="image about bar">
                <h3>Replenish your strength</h3>
                <p>
                    Cold-pressed juice refers to juice that uses a hydraulic press to extract juice from
                    fruit and vegetables.
                </p>
            </div>
        </div>

    </div>
</section>
<section class="map">
    <iframe frameborder="0" scrolling="no"
            src="https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;q=sauletekio%20al%2015+(My%20Business%20Name)&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"></iframe>
</section>
<!--<h2 class="heading">--><?php //print $data['heading'] ?><!--</h2>-->

<!-- All the pizza items will be generated by JS in this container -->
<section id="pizza-grid-container"></section>

<!-- Create form can be pre-rendered -->
<?php if (isset($data['forms']['create'])): ?>
    <div class="create-form-wrapper">
        <?php print $data['forms']['create']; ?>
    </div>
<?php endif; ?>

<!-- Update Modal (Popup)-->
<?php if (isset($data['forms']['update'])): ?>
    <div id="update-modal" class="modal">
        <div class="wrapper">
            <span class="close">&times;</span>
            <?php print $data['forms']['update']; ?>
        </div>
    </div>
<?php endif; ?>

<?php foreach ($data['links'] as $link): ?>
    <?php print $link; ?>
<?php endforeach; ?>

